# refresh: 4
# https://github.com/actions/starter-workflows/blob/main/pages/static.yml
# https://github.com/tschaub/gh-pages
# https://maxschmitt.me/posts/github-actions-ssh-key
# https://github.com/webfactory/ssh-agent

# to create your key:
#   ssh-keygen -t ed25519 -a 100 -f path/to/keyfile -N "" -C "github-actions"
# make sure no passphrase, can't get prompted in github secret
# if you need older rsa method for older servers:
#   ssh-keygen -t rsa -b 4096 -o -f path/to/keyfile -N "" -C "github-actions"
# on the source repo: add the file contents without an extension to ACTIONS_DEPLOY_KEY secrets
#   repo -> settings -> environments -> github-pages -> Environment secrets -> add ACTIONS_DEPLOY_KEY secret -> paste in contents
# make sure there is a trailing newline at the end. It will fail otherwise.
# also, if you use environment secret here, you need to use `environment: github-pages` below. Otherwise use a repository secret instead.
# on the destination repo: add the file contents of the .pub file to deploy keys
#   repo -> settings -> Security header -> Deploy keys -> Add deploy key -> check write access
# make sure both files use linux LF characters, not windows ones.
# if you have a copy paste / clipboard utility or some other program it may mangle the contents.
#
# if you private key does not have `BEGIN OPENSSH PRIVATE KEY` in header you NEED to convert to PEM (make a backup of your key first):
#   ssh-keygen -p -f path/to/your/key -m pem

name: Deploy to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read # fine because ssh deploy key will have the write at the destination 
  # pages: write # since we are ssh pushing, don't need this
  # id-token: write # since we are ssh pushing, don't need this

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest    
    environment: github-pages
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        
      - name: Configure Git for SSH
        run: |
          git config --global user.email "support+actions@github.com"
          git config --global user.name "github-actions-bot"

          # notice github.com: not github.com/ for ssh url
          git remote set-url origin git@github.com:test-ghpages-deploy/test-ghpages-deploy.github.io.git

          git remote -v # Debug check: should show SSH URL
        env:
          SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}

      - name: Test SSH access
        run: |
          ssh -T git@github.com || true
        env:
          SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}

      - name: Deploy to GitHub Pages
        id: deployment
        run: |
          NODE_DEBUG=gh-pages npx gh-pages --dist build --branch main
        env:
          SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}
        if: ${{ github.ref == 'refs/heads/main' }} # only deploy main
          
