# https://github.com/tschaub/gh-pages
name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Deploy to GitHub Pages
        id: deployment
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/test-ghpages-deploy/test-ghpages-deploy.github.io.git
          npx gh-pages --dist build --branch main --user "github-actions-bot <support+actions@github.com>"
        if: ${{ github.ref == 'refs/heads/main' }} # only deploy main
        env:
          DEST_VAR: ${{ vars.REPOSITORY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
